import mongoose from "mongoose";
const schema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    title: { type: String, required: true, trim: true },
    company: { type: String, required: true, trim: true },
    location: String,
    remoteType: {
      type: String,
      enum: ["ONSITE", "HYBRID", "REMOTE"],
      default: "HYBRID",
    },
    employmentType: {
      type: String,
      enum: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP", "FREELANCE"],
      default: "FULL_TIME",
    },
    jobUrl: String,
    companyUrl: String,
    salaryMin: Number,
    salaryMax: Number,
    currency: { type: String, default: "USD" },
    description: String,
    status: {
      type: String,
      enum: [
        "SAVED",
        "APPLIED",
        "SCREENING",
        "INTERVIEW",
        "TECHNICAL_INTERVIEW",
        "FINAL_INTERVIEW",
        "OFFER",
        "ACCEPTED",
        "REJECTED",
        "WITHDRAWN",
      ],
      default: "SAVED",
      index: true,
    },
    appliedDate: Date,
    interviewDate: Date,
    followUpDate: Date,
    offerDate: Date,
    contactName: String,
    contactEmail: String,
    contactPhone: String,
    source: { type: String, default: "Other" },
    priority: {
      type: String,
      enum: ["LOW", "MEDIUM", "HIGH"],
      default: "MEDIUM",
    },
    notes: String,
    tags: [String],
  },
  { timestamps: true },
);
export default mongoose.model("Job", schema);
